# @name listar_filme_por_pagina
GET http://localhost:3333/filme/listar/2

########

# @name listar_filme_generos

GET http://localhost:3333/filme/listar/genero

########

# @name listar_filme_por_nome

GET http://localhost:3333/filme/buscar?query=five

########


# @name buscar_filme_por_id

GET http://localhost:3333/filme/buscar/872585

########

# @name listar_serie_por_nome

GET http://localhost:3333/serie/buscar?query=five

########

# @name listar_serie_por_pagina
GET http://localhost:3333/serie/listar/1

########

# @name listar_serie_generos

GET http://localhost:3333/serie/listar/genero

########


# @name create-transcription

POST http://localhost:3333/user/login
Content-Type: application/json

{
  "email": "a@a.com",
  "password": "1234"
}

########

# @name listar_serie_generos

GET http://localhost:3333/user/listar

########
